CREATE DATABASE nimitilastot;
USE nimitilastot;
CREATE TABLE men_all (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE men_other (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE men_first (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE women_all (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE women_other (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE women_first (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
CREATE TABLE lastnames (name VARCHAR(20) NOT NULL, count MEDIUMINT UNSIGNED NOT NULL);
